# Generated by Django 3.1.5 on 2021-02-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.BooleanField(default=False, verbose_name='Add')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('update', models.BooleanField(default=False, verbose_name='Update')),
                ('view', models.BooleanField(default=False, verbose_name='View')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
    ]
